export const CSP_DOMAINS = {
  google: {
    script: [
      'https://translate.googleapis.com',
      'https://translate.google.com',
      'https://pagead2.googlesyndication.com',
      'https://translate-pa.googleapis.com',
      'https://www.googletagmanager.com',
      'https://www.google-analytics.com',
      'https://www.gstatic.com',
    ],
    style: [
      'https://translate.googleapis.com',
      'https://translate.google.com',
      'https://www.gstatic.com',
      'https://pagead2.googlesyndication.com',
      'https://fonts.googleapis.com',
    ],
    img: [
      'https://fonts.gstatic.com',
      'https://www.gstatic.com',
      'https://www.google.com',
      'https://translate.googleapis.com',
      'http://translate.google.com',
      'https://translate.google.com',
      'https://pagead2.googlesyndication.com',
      'https://www.googletagmanager.com',
      'https://www.google-analytics.com',
    ],
    font: ['https://fonts.gstatic.com'],
    frame: [
      'https://translate.google.com',
      'https://accounts.google.com',
      'https://www.googletagmanager.com',
      'https://pagead2.googlesyndication.com',
    ],
    connect: [
      'https://translate.googleapis.com',
      'https://translate-pa.googleapis.com',
      'https://www.googletagmanager.com',
      'https://pagead2.googlesyndication.com',
      'https://www.google-analytics.com',
    ],
  },
};
